-- Text moderation: configurable banned substring list + version; enforced on DB triggers.

CREATE TABLE IF NOT EXISTS public.moderation_config (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  list_version TEXT NOT NULL DEFAULT '2026-04-15-1'
);

INSERT INTO public.moderation_config (id, list_version)
VALUES (1, '2026-04-15-1')
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE public.moderation_config IS 'Singleton row: bump list_version when moderation_terms changes meaningfully.';

CREATE TABLE IF NOT EXISTS public.moderation_terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT moderation_terms_term_unique UNIQUE (term)
);

COMMENT ON TABLE public.moderation_terms IS 'Banned substrings (case-insensitive). Update via SQL; bump moderation_config.list_version.';

ALTER TABLE public.moderation_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moderation_terms ENABLE ROW LEVEL SECURITY;

-- No policies: only service role / postgres manage rows; app uses SECURITY DEFINER RPC + triggers.

CREATE OR REPLACE FUNCTION public.moderation_text_is_allowed(p_text TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NOT EXISTS (
    SELECT 1
    FROM public.moderation_terms t
    WHERE t.active
      AND length(trim(t.term)) > 0
      AND position(lower(trim(t.term)) IN lower(trim(COALESCE(p_text, '')))) > 0
  );
$$;

COMMENT ON FUNCTION public.moderation_text_is_allowed(TEXT) IS 'True if text does not contain any active banned substring.';

CREATE OR REPLACE FUNCTION public.moderation_list_version()
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT list_version FROM public.moderation_config WHERE id = 1;
$$;

GRANT EXECUTE ON FUNCTION public.moderation_text_is_allowed(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderation_text_is_allowed(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.moderation_list_version() TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderation_list_version() TO service_role;

CREATE OR REPLACE FUNCTION public.enforce_moderation_profiles_display_name()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.display_name IS NOT NULL AND length(trim(NEW.display_name)) > 0 THEN
    IF NOT public.moderation_text_is_allowed(NEW.display_name) THEN
      RAISE EXCEPTION 'This text is not allowed under our community guidelines.'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_display_name_moderation ON public.profiles;
CREATE TRIGGER profiles_display_name_moderation
  BEFORE INSERT OR UPDATE OF display_name ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_moderation_profiles_display_name();

CREATE OR REPLACE FUNCTION public.enforce_moderation_recommendations_message()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.message IS NOT NULL AND length(trim(NEW.message)) > 0 THEN
    IF NOT public.moderation_text_is_allowed(NEW.message) THEN
      RAISE EXCEPTION 'This message is not allowed under our community guidelines.'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS recommendations_message_moderation ON public.recommendations;
CREATE TRIGGER recommendations_message_moderation
  BEFORE INSERT OR UPDATE OF message ON public.recommendations
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_moderation_recommendations_message();

-- Auth signup: avoid inserting a display_name that fails moderation (would break signup).
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_display TEXT;
BEGIN
  v_display := COALESCE(NEW.raw_user_meta_data->>'name', NEW.email);
  IF v_display IS NOT NULL AND length(trim(v_display)) > 0 AND NOT public.moderation_text_is_allowed(v_display) THEN
    v_display := 'User';
  END IF;
  INSERT INTO public.profiles (id, display_name, email)
  VALUES (NEW.id, v_display, NEW.email);
  RETURN NEW;
END;
$$;
